export const FilterDatas = [
  {
    title: "Category",
    items: [
      { name: "Footwear", count: "[250]", value: "footwear" },
      { name: "Apparel", count: "[250]", value: "apparel" },
      { name: "Accessories", count: "[250]", value: "accessories" },
    ],
  },
  {
    title: "Price",
    range: {
      min: 199,
      max: 45999,
    },
  },
  {
    title: "Gender",
    items: [
      { name: "Boys", count: " [2]", value: "boys" },
      { name: "Female ", count: "[7]", value: "female" },
      { name: "Male ", count: "[2640]", value: "male" },
      { name: "Unisex ", count: "[173]", value: "unisex" },
      { name: "Unisex - Adults ", count: "[1288]", value: "unisex-adults" },
      { name: "Unisex - Kids ", count: "[1]", value: "unisex-kids" },
    ],
  },
  {
    title: "Size",
    items: [
      { name: "UA", value: "ua" },
      { name: "OSFA", value: "osfa" },
      { name: "33", value: "33" },
      { name: "34", value: "34" },
      { name: "35", value: "35" },
      { name: "36", value: "36" },
      { name: "38", value: "38" },
      { name: "40", value: "40" },
      { name: "26", value: "26" },
      { name: "28", value: "28" },
      { name: "29", value: "29" },
      { name: "30", value: "30" },
      { name: "31", value: "31" },
      { name: "32", value: "32" },
      { name: "XXS", value: "xxs" },
      { name: "XS", value: "xs" },
      { name: "S", value: "s" },
      { name: "S/M", value: "s-m" },
      { name: "M", value: "m" },
      { name: "M/L", value: "m-l" },
      { name: "L", value: "l" },
      { name: "L/XL", value: "l-xl" },
      { name: "XL", value: "xl" },
      { name: "XXL", value: "xxl" },
      { name: "3XL", value: "3xl" },
      { name: "4XL", value: "4xl" },
      { name: "6-8", value: "6-8" },
      { name: "3", value: "3" },
      { name: "4", value: "4" },
      { name: "5", value: "5" },
    ],
  },
  {
    title: "Color",
    items : [
        { name: "Black", count:"[1435]", value: "black", bgColor: "#000000" },
        { name: "Gray ", count:"[15]", value: "gray", bgColor: "#808080" },
        { name: "Brown", count:"[35]", value: "brown", bgColor: "#A52A2A" },
        { name: "Blue ", count:"[145]", value: "blue", bgColor: "#0000FF" },
        { name: "Green ", count:"[305]", value: "green", bgColor: "#008000" },
        { name: "Orange", count:"[145]", value: "orange", bgColor: "#FFA500" },
        { name: "Tan", count:"[95]", value: "tan", bgColor: "#D2B48C" },
        { name: "Yellow", count:"[135]", value: "yellow", bgColor: "#FFFF00" },
        { name: "Red ", count:"[145]", value: "red", bgColor: "#FF0000" },
        { name: "Purple", count:"[105]", value: "purple", bgColor: "#800080" },
        { name: "Pink", count:"[435]", value: "pink", bgColor: "#FFC0CB" },
        { name: "White ", count:"[15]", value: "white", bgColor: "#FFFFFF" },
        { name: "Multi-Colored", count:"[1435]", value: "multi-colored", bgColor: "linear-gradient(45deg, #FF0000, #0000FF, #FFFF00, #008000)" },
      ]
  },
  {
    title: "Discount",
    items: [
        { name: "15", count: "[13]", value: "15" },
        { name: "less than 20", count: "[53]", value: "less-than-20" },
        { name: "20-29", count: "[151]", value: "20-29" },
        { name: "30-39", count: "[573]", value: "30-39" },
      ]
  },
];
